#!/usr/bin/env bash
# Creates  loop with multiple iterations using 'while, if, elif' and 'else'

a=1
while
	[ $a -le 10 ]
do
	if [ $a -eq 4 ]
	then
		echo "bad luck"

	elif [ $a -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((a++))
done
