#!/usr/bin/env bash
# Using the while loop and case statement the script will show numbers 1-20 w some special instructions

a=1
while
	[ $a -le 20 ]
	do
	echo "$a"
	case $a in
		4) echo "bad luck from China"
		;;
		9) echo "bad luck from Japan"
		;;
		17) echo "bad luck from Italy"
		;;
	esac
	((a++))
	done
